### ISSUE TITLE
comments sexy

### ISSUE THREAD

**Issue by xavierartot** [mathaywarduk/simple-sass-framework#1]
Hi,
I wonder wich plugin do you use to got the comments here:
https://github.com/mathaywarduk/simple-sass-framework/blob/master/assets/sass/screen.scss
It's a Vim plugin?
Thank you

**Comment by mathaywarduk** [comment]
Such a long time ago but I think they were manually styled.

Since then, I've started to use this: https://github.com/chrisborrowdale/Idiomatic-CSS-Comments-Snippets
